### YamlMime:Yaml
ms.openlocfilehash: 942b6ae523b9cb5e8608d6fbe2882737415dcd51
ms.sourcegitcommit: f3937681c3f6e310355071e1842967695e365751
ms.translationtype: HT
ms.contentlocale: zh-CN
ms.lasthandoff: 10/29/2021
ms.locfileid: "130738809"
trigger:
- main
resources:
- repo: self
### YamlMime:Yaml
ms.openlocfilehash: 0d95a85946c3580c7a678d53afddbfa5ee08209f
ms.sourcegitcommit: f3937681c3f6e310355071e1842967695e365751
ms.translationtype: HT
ms.contentlocale: zh-CN
ms.lasthandoff: 10/29/2021
ms.locfileid: "130738809"
variables:
  dockerfilePath: $(Build.SourcesDirectory)/src/Dockerfile
  webRepository: web
  tag: $(Build.BuildId)
  vmImageName: ubuntu-latest
### YamlMime:Yaml
ms.openlocfilehash: 652994a291aa8f3a4880d13a0a8fa212e86f1275
ms.sourcegitcommit: f3937681c3f6e310355071e1842967695e365751
ms.translationtype: HT
ms.contentlocale: zh-CN
ms.lasthandoff: 10/29/2021
ms.locfileid: "130738809"
stages:
- stage: Build
  displayName: Build and publish Java container
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    variables:
    - group: Release
    steps:
- task: Maven@3
  displayName: Maven pom.xml
  inputs:
    options: '-DskipITs --settings ./maven/settings.xml'
    publishJUnitResults: false
- task: CopyFiles@2
  displayName: Copy WAR file to staging directory
  inputs:
    sourceFolder: $(build.sourcesdirectory)
    contents: |
      target/myshuttledev*.war
      *.sql
    targetFolder: $(build.artifactstagingdirectory)
- task: Docker@2
  displayName: Build and push Java container image to registry
  inputs:
    command: buildAndPush
    buildContext: $(build.artifactstagingdirectory)
    repository: $(webRepository)
    dockerfile: $(dockerfilePath)
    containerRegistry: Container Registry Connection
    tags: |
      $(tag)
- task: AzureMysqlDeployment@1
  displayName: Run MySQL initialization script
  inputs:
    azureSubscription: Azure Connection
    serverName: $(MySqlServer).mysql.database.azure.com
    databaseName: alm
    sqlUsername: $(MySqlUserName)@$(MySqlServer)
    sqlPassword: $(MySqlPassword)
    sqlFile: $(Build.SourcesDirectory)/CreateMYSQLDB.sql
- stage: Deploy
  displayName: Deploy Web App
  dependsOn: Build
  condition: succeeded()
  jobs:
    - deployment: DeploymentJob
      pool:
        vmImage: $(vmImageName)
      environment: java-container
      variables:
        - group: Release
      strategy:
        runOnce:
          deploy:
            steps: null
- task: AzureWebAppContainer@1
  displayName: Update the web app with the new container
  inputs:
    appName: $(WebAppName)
    azureSubscription: Azure Connection
    imageName: '$(RegistryName)/$(webRepository):$(build.buildId)'
- task: AzureAppServiceSettings@1
  displayName: Update web app connection string
  inputs:
    azureSubscription: Azure Connection
    appName: $(WebAppName)
    resourceGroupName: java-containers-cicd-rg
    connectionStrings: |
      [
        {
          "name": "MyShuttleDb",
          "value": "jdbc:mysql://$(MySqlServer).mysql.database.azure.com:3306/alm?useSSL=true&requireSSL=false&autoReconnect=true&user=$(MySqlUserName)@$(MySqlServer)&password=$(MySqlPassword)",
          "type": "MySql",
          "slotSetting": false
        }
      ]